name: Build and Publish Home Assistant Add-on

on:
  push:
    tags:
      - '*'            # Run on any tag (e.g. v1.5.2 or 1.5.2)
  workflow_dispatch:    # Allow manual run from Actions tab

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: deeppurple77/ha-whatsapp-addon

jobs:
  build:
    name: Build and Push Multi-Arch Image
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU (for cross-building)
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push multi-arch image
        uses: docker/build-push-action@v6
        with:
          file: ./ha-whatsapp-addon/Dockerfile
	  push: true
          platforms: linux/amd64,linux/armv7,linux/aarch64,linux/386,linux/armhf
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

