name: Build and Publish Add-on

on:
  push:
    tags:
      - "*" # build when a tag (e.g. 1.5.2) is pushed
  workflow_dispatch: # allow manual builds

jobs:
  build:
    name: Build multi-arch image
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write # required for GHCR push
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: ./whatsapp_addon
          file: ./whatsapp_addon/Dockerfile
          platforms: linux/amd64,linux/arm64, linux/arm/v6, linux/arm/v7, linux/386
          push: true
          tags: |
            ghcr.io/deeppurple77/ha-whatsapp-addon:latest
            ghcr.io/deeppurple77/ha-whatsapp-addon:${{ github.event.release.tag_name || github.ref_name }}

      - name: Make GHCR image public
        run: |
          curl -s -X PATCH \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/user/packages/container/ha-whatsapp-addon/visibility \
            -d '{"visibility":"public"}'

